# Generated by Django 5.2.5 on 2025-09-11 12:44

import apps.core.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Validé"),
                            (2, "En attente"),
                            (3, "Annulé"),
                            (4, "Reporté"),
                            (5, "Terminé"),
                            (6, "Absent"),
                        ],
                        default=2,
                    ),
                ),
                ("date", models.DateTimeField()),
                ("subject", models.CharField(max_length=200)),
                (
                    "notes",
                    tinymce.models.HTMLField(
                        blank=True, null=True, verbose_name="Notes"
                    ),
                ),
                (
                    "report",
                    tinymce.models.HTMLField(
                        blank=True,
                        null=True,
                        verbose_name="compte rendu de rendez-vous",
                    ),
                ),
            ],
            options={
                "verbose_name": "rendez-vous",
                "verbose_name_plural": "rendez-vous",
                "ordering": ["date"],
            },
            bases=(apps.core.models.CRUDUrlMixin, models.Model),
        ),
    ]
