# Generated by Django 5.2.5 on 2025-09-11 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointment", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="appointments", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
