# Generated by Django 5.2.5 on 2025-09-11 12:44

import apps.core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bill_number",
                    models.CharField(max_length=50, unique=True, verbose_name="Numéro"),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'échéance"
                    ),
                ),
                (
                    "creation_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Creation date"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "state",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "En attente"),
                            (2, "Envoyé"),
                            (3, "Partiellement payé"),
                            (4, "Payé"),
                            (5, "Annulé"),
                        ],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
                "ordering": ["-created_at"],
            },
            bases=(apps.core.models.CRUDUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True, default=1, null=True, verbose_name="Quantité"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Unité"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Réduction sur le total de la ligne",
                        max_digits=10,
                        null=True,
                        verbose_name="Remise",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Prix total",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Item",
                "verbose_name_plural": "Invoice Items",
                "ordering": ["bill", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bill_number",
                    models.CharField(max_length=50, unique=True, verbose_name="Numéro"),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'échéance"
                    ),
                ),
                (
                    "creation_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Creation date"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "state",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "En attente"),
                            (2, "Envoyé"),
                            (3, "Accepté"),
                            (4, "Refusé"),
                            (5, "Annulé"),
                        ],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="date d'expiration"
                    ),
                ),
            ],
            options={
                "verbose_name": "Devis",
                "verbose_name_plural": "Devis",
                "ordering": ["-created_at"],
            },
            bases=(apps.core.models.CRUDUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name="QuoteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True, default=1, null=True, verbose_name="Quantité"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Unité"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Réduction sur le total de la ligne",
                        max_digits=10,
                        null=True,
                        verbose_name="Remise",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Prix total",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Quote Item",
                "verbose_name_plural": "Quote Items",
                "ordering": ["bill", "display_order"],
            },
        ),
    ]
