# Generated by Django 5.2.5 on 2025-09-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="bill_discount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Remise"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="bill_total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Montant total"
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="bill_discount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Remise"
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="bill_total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Montant total"
            ),
        ),
    ]
