# Generated by Django 5.2.5 on 2025-09-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_invoice_bill_discount_invoice_bill_total_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="bill_discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Remise sur le total de la facture.",
                max_digits=10,
                null=True,
                verbose_name="Remise",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="bill_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Applicable seulement si vous ne souhaitez pas utiliser les lignes de facture.",
                max_digits=10,
                null=True,
                verbose_name="Montant total",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="bill_discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Remise sur le total de la facture.",
                max_digits=10,
                null=True,
                verbose_name="Remise",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="bill_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Applicable seulement si vous ne souhaitez pas utiliser les lignes de facture.",
                max_digits=10,
                null=True,
                verbose_name="Montant total",
            ),
        ),
    ]
