# Generated by Django 5.2.5 on 2025-09-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "billing",
            "0005_alter_invoice_bill_discount_alter_invoice_bill_total_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Prix",
            ),
        ),
        migrations.AlterField(
            model_name="quoteitem",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Prix",
            ),
        ),
    ]
