# Generated by Django 5.2.5 on 2025-09-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_alter_invoiceitem_unit_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="title",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Titre"
            ),
        ),
        migrations.AlterField(
            model_name="quoteitem",
            name="title",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Titre"
            ),
        ),
    ]
