# Generated by Django 5.2.5 on 2025-09-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0008_remove_invoice_created_by_remove_invoice_lead_and_more"),
        (
            "transactions",
            "0007_remove_clientpayment_invoice_clientpayment_bill_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Invoice",
        ),
        migrations.DeleteModel(
            name="InvoiceItem",
        ),
        migrations.DeleteModel(
            name="Quote",
        ),
        migrations.DeleteModel(
            name="QuoteItem",
        ),
        migrations.AddConstraint(
            model_name="bill",
            constraint=models.UniqueConstraint(
                fields=("bill_type", "bill_year", "bill_number"),
                name="unique_bill_number_per_type_year",
            ),
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
                "ordering": ["-created_at"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("billing.bill",),
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[],
            options={
                "verbose_name": "Devis",
                "verbose_name_plural": "Devis",
                "ordering": ["-created_at"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("billing.bill",),
        ),
    ]
