# Generated by Django 5.2.5 on 2025-09-17 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0009_delete_invoice_delete_invoiceitem_delete_quote_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Titre"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True, default=1, null=True, verbose_name="Quantité"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Prix",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Unité"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Réduction sur le total de la ligne",
                        max_digits=10,
                        null=True,
                        verbose_name="Remise",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Prix total",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="billing.bill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bill Line",
                "verbose_name_plural": "Bill Lines",
                "ordering": ["bill", "description"],
            },
        ),
    ]
