# Generated by Django 5.2.5 on 2025-09-11 12:44

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="B2BLeadState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Nouveau"),
                            (2, "Non traité"),
                            (3, "Non qualifié"),
                            (4, "Qualifié"),
                            (5, "Injoignable"),
                            (6, "Non intéressé"),
                            (7, "Client dupliqué"),
                            (8, "Perdue"),
                            (9, "Gagnée"),
                        ],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Note")),
            ],
        ),
        migrations.CreateModel(
            name="B2CLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Source"
                    ),
                ),
                (
                    "current_state",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Latest state from LeadState",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "B2C Opportunité",
                "verbose_name_plural": "B2C Opportunités",
                "ordering": ["-created_at"],
            },
            bases=(apps.core.models.CRUDUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name="B2CLeadState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Nouveau"),
                            (2, "Non traité"),
                            (3, "Non qualifié"),
                            (4, "Qualifié"),
                            (5, "Injoignable"),
                            (6, "Non intéressé"),
                            (7, "Client dupliqué"),
                            (8, "Perdue"),
                            (9, "Gagnée"),
                        ],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Note")),
            ],
        ),
        migrations.CreateModel(
            name="B2BLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Source"
                    ),
                ),
                (
                    "current_state",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Latest state from LeadState",
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="crm.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "B2B Opportunité",
                "verbose_name_plural": "B2B Opportunités",
                "ordering": ["-created_at"],
            },
            bases=(apps.core.models.CRUDUrlMixin, models.Model),
        ),
    ]
