# Generated by Django 5.2.5 on 2025-09-11 12:44

import apps.core.models
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_company",
                    models.CharField(
                        max_length=100, verbose_name="Nom de l'entreprise"
                    ),
                ),
                (
                    "name_company_arabic",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="اسم الشركة"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/logos",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "logo_negatif",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/slides",
                        verbose_name="Logo négatif",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/logos",
                        verbose_name="Favicon",
                    ),
                ),
                (
                    "business_owner",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="nom et prenom"
                    ),
                ),
                (
                    "business_owner_arabic",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="الاسم واللقب",
                    ),
                ),
                ("wilaya", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Address"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="e-mail entreprise",
                    ),
                ),
                (
                    "email2",
                    models.EmailField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="e-mail 2 entreprise",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="numéro de téléphone de l'entreprise",
                    ),
                ),
                (
                    "phone2",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="numéro de téléphone 2 de l'entreprise",
                    ),
                ),
                (
                    "phone3",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="numéro de téléphone 3 de l'entreprise",
                    ),
                ),
                (
                    "mini_about",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        null=True,
                        verbose_name="Description 1",
                    ),
                ),
                (
                    "about",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        null=True,
                        verbose_name="Description 2",
                    ),
                ),
                (
                    "rc_code",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Registre de commerce",
                    ),
                ),
                (
                    "art_code",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Code d'article",
                    ),
                ),
                (
                    "nif_code",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Numéro d'identité fiscale",
                    ),
                ),
                (
                    "nis_code",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Numéro d'identification statistique",
                    ),
                ),
                (
                    "bank_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Numéro CCP / RIB",
                    ),
                ),
                (
                    "bank_info",
                    tinymce.models.HTMLField(
                        blank=True,
                        null=True,
                        verbose_name="Informations CCP, nom, prénom, adresse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Settings",
                "verbose_name_plural": "Business Settings",
            },
            bases=(apps.core.models.CRUDUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name="BusinessSocials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "social_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Facebook"),
                            (2, "Instagram"),
                            (3, "Twitter"),
                            (4, "LinkedIn"),
                            (5, "Pinterest"),
                            (6, "Snapchat"),
                            (7, "TikTok"),
                            (8, "YouTube"),
                        ],
                        verbose_name="Social Type",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True, max_length=300, null=True, verbose_name="Link"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Is Primary"),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="socials",
                        to="business.businesssettings",
                        verbose_name="Business Settings",
                    ),
                ),
            ],
        ),
    ]
