# Generated by Django 5.2.5 on 2025-09-11 12:44

import apps.core.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InvoicePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Virement bancaire"),
                            ("payment_card", "Carte de paiement"),
                        ],
                        default="cash",
                        max_length=64,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=11,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Montant",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Paiement Facture",
                "verbose_name_plural": "Paiements Facture",
                "ordering": ["-date"],
                "abstract": False,
            },
            bases=(apps.core.models.CRUDUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.CharField(
                        help_text="User who created this entry", max_length=100
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("description", models.CharField(max_length=255)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense")],
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=11,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "account",
                    models.CharField(
                        help_text="Account name affected by this entry (e.g., Cash, Revenue)",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ledger Entry",
                "verbose_name_plural": "Ledger Entries",
                "ordering": ["-date"],
            },
            bases=(models.Model, apps.core.models.CRUDUrlMixin),
        ),
        migrations.CreateModel(
            name="MiscTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Virement bancaire"),
                            ("payment_card", "Carte de paiement"),
                        ],
                        default="cash",
                        max_length=64,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=11,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Montant",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                ("notes", models.TextField(blank=True, null=True)),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("income", "Income"),
                            ("expense", "Expense"),
                            ("refund", "Refund"),
                        ],
                        default="income",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Autre Transaction",
                "verbose_name_plural": "Autres Transactions",
                "ordering": ["-date"],
                "abstract": False,
            },
            bases=(apps.core.models.CRUDUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name="StaffPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Virement bancaire"),
                            ("payment_card", "Carte de paiement"),
                        ],
                        default="cash",
                        max_length=64,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=11,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Montant",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Paiement Personnel",
                "verbose_name_plural": "Paiements Personnels",
                "ordering": ["-date"],
                "abstract": False,
            },
            bases=(apps.core.models.CRUDUrlMixin, models.Model),
        ),
    ]
