# Generated by Django 5.2.5 on 2025-09-11 12:44

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0002_initial"),
        ("crm", "0001_initial"),
        ("transactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicepayment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="invoicepayment",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="billing.invoice",
                verbose_name="Facture",
            ),
        ),
        migrations.AddField(
            model_name="invoicepayment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="invoice_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_entries",
                to="transactions.invoicepayment",
            ),
        ),
        migrations.AddField(
            model_name="misctransaction",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="misc_transactions",
                to="crm.contact",
            ),
        ),
        migrations.AddField(
            model_name="misctransaction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="misctransaction",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="misc_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_entries",
                to="transactions.misctransaction",
            ),
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
                "ordering": ["-date"],
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("transactions.misctransaction", apps.core.models.CRUDUrlMixin),
        ),
        migrations.CreateModel(
            name="Income",
            fields=[],
            options={
                "verbose_name": "Income",
                "verbose_name_plural": "Incomes",
                "ordering": ["-date"],
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("transactions.misctransaction", apps.core.models.CRUDUrlMixin),
        ),
        migrations.AddField(
            model_name="staffpayment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="staffpayment",
            name="staff_member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Membre du personnel",
            ),
        ),
        migrations.AddField(
            model_name="staffpayment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="staff_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_entries",
                to="transactions.staffpayment",
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("invoice_payment__isnull", True),
                        ("misc_transaction__isnull", True),
                        ("staff_payment__isnull", True),
                    ),
                    models.Q(
                        ("invoice_payment__isnull", False),
                        ("misc_transaction__isnull", True),
                        ("staff_payment__isnull", True),
                    ),
                    models.Q(
                        ("invoice_payment__isnull", True),
                        ("misc_transaction__isnull", True),
                        ("staff_payment__isnull", True),
                    ),
                    models.Q(
                        ("invoice_payment__isnull", True),
                        ("misc_transaction__isnull", True),
                        ("staff_payment__isnull", False),
                    ),
                    models.Q(
                        ("invoice_payment__isnull", True),
                        ("misc_transaction__isnull", False),
                        ("staff_payment__isnull", True),
                    ),
                    models.Q(
                        ("invoice_payment__isnull", True),
                        ("misc_transaction__isnull", True),
                        ("staff_payment__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="exactly_one_transaction_fk",
            ),
        ),
    ]
