# Generated by Django 5.2.5 on 2025-09-16 17:57

import apps.core.models
import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_alter_invoiceitem_title_alter_quoteitem_title"),
        ("crm", "0002_initial"),
        ("transactions", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Virement bancaire"),
                            ("payment_card", "Carte de paiement"),
                        ],
                        default="cash",
                        max_length=64,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=11,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Montant",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                ("reference", models.CharField(blank=True, max_length=200, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Paiement Facture",
                "verbose_name_plural": "Paiements Facture",
                "ordering": ["-date"],
                "abstract": False,
            },
            bases=(apps.core.models.CRUDUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("bank", "Bank"),
                            ("cash", "Cash"),
                            ("other", "Other"),
                        ],
                        default="bank",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.RemoveField(
            model_name="invoicepayment",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="invoicepayment",
            name="invoice",
        ),
        migrations.RemoveField(
            model_name="invoicepayment",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="ledgerentry",
            name="invoice_payment",
        ),
        migrations.AddField(
            model_name="misctransaction",
            name="reference",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="staffpayment",
            name="reference",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="clientpayment",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="crm.company",
            ),
        ),
        migrations.AddField(
            model_name="clientpayment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="clientpayment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="client_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_entries",
                to="transactions.clientpayment",
            ),
        ),
        migrations.AddField(
            model_name="clientpayment",
            name="journal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="transactions.journal",
            ),
        ),
        migrations.AddField(
            model_name="misctransaction",
            name="journal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="transactions.journal",
            ),
        ),
        migrations.AddField(
            model_name="staffpayment",
            name="journal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="transactions.journal",
            ),
        ),
        migrations.AddField(
            model_name="paymentinvoice",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="billing.invoice"
            ),
        ),
        migrations.AddField(
            model_name="paymentinvoice",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.clientpayment",
            ),
        ),
        migrations.AddField(
            model_name="clientpayment",
            name="invoices",
            field=models.ManyToManyField(
                related_name="payments",
                through="transactions.PaymentInvoice",
                to="billing.invoice",
            ),
        ),
        migrations.DeleteModel(
            name="InvoicePayment",
        ),
    ]
