# Generated by Django 5.2.5 on 2025-09-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_clientpayment_journal_paymentinvoice_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("client_payment__isnull", False),
                        ("misc_transaction__isnull", True),
                        ("staff_payment__isnull", True),
                    ),
                    models.Q(
                        ("client_payment__isnull", True),
                        ("misc_transaction__isnull", True),
                        ("staff_payment__isnull", False),
                    ),
                    models.Q(
                        ("client_payment__isnull", True),
                        ("misc_transaction__isnull", False),
                        ("staff_payment__isnull", True),
                    ),
                    models.Q(
                        ("client_payment__isnull", True),
                        ("misc_transaction__isnull", True),
                        ("staff_payment__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="exactly_one_transaction_fk",
            ),
        ),
    ]
