# Generated by Django 5.2.5 on 2025-09-16 19:01

import django.db.models.deletion
from django.db import migrations, models

def set_client_from_invoice(apps, schema_editor):
    ClientPayment = apps.get_model("transactions", "ClientPayment")
    for payment in ClientPayment.objects.filter(client__isnull=True, invoice__isnull=False):
        # set client from related invoice.lead.company
        invoice = payment.invoice
        if invoice and getattr(invoice, "lead", None) and getattr(invoice.lead, "company", None):
            payment.client = invoice.lead.company
            payment.save(update_fields=["client"])

class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_alter_invoiceitem_title_alter_quoteitem_title"),
        ("transactions", "0004_remove_ledgerentry_exactly_one_transaction_fk_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ledgerentry",
            name="exactly_one_transaction_fk",
        ),
        migrations.RemoveField(
            model_name="clientpayment",
            name="invoices",
        ),
        migrations.AddField(
            model_name="clientpayment",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="billing.invoice",
            ),
        ),
        migrations.RunPython(set_client_from_invoice, migrations.RunPython.noop),

    ]
