# Generated by Django 5.2.5 on 2025-09-16 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_initial"),
        ("transactions", "0005_remove_ledgerentry_exactly_one_transaction_fk_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientpayment",
            name="client",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="crm.company",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("client_payment__isnull", False),
                        ("misc_transaction__isnull", True),
                        ("staff_payment__isnull", True),
                    ),
                    models.Q(
                        ("client_payment__isnull", True),
                        ("misc_transaction__isnull", True),
                        ("staff_payment__isnull", False),
                    ),
                    models.Q(
                        ("client_payment__isnull", True),
                        ("misc_transaction__isnull", False),
                        ("staff_payment__isnull", True),
                    ),
                    models.Q(
                        ("client_payment__isnull", True),
                        ("misc_transaction__isnull", True),
                        ("staff_payment__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="exactly_one_transaction_fk",
            ),
        ),
    ]
