# Generated by Django 5.2.5 on 2025-09-17 16:10

import django.db.models.deletion
from django.db import migrations, models
from decimal import Decimal
from django.utils import timezone

def create_default_bill(apps, schema_editor):
    """
    Data migration helper: ensure a Bill exists (pk=1) so FK defaults can point to it.
    Tries to fill required fields with reasonable placeholders if needed.
    """
    Bill = apps.get_model("billing", "Bill")

    if Bill.objects.filter(pk=1).exists():
        return
    Bill.objects.create(
        pk=1,
        bill_year=timezone.now().year
    )  # Try to create with minimal fields first


def noop_reverse(apps, schema_editor):
    # Intentionally no-op; keep the created Bill in place.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0008_remove_invoice_created_by_remove_invoice_lead_and_more"),
        ("transactions", "0006_alter_clientpayment_client_and_more"),
    ]

    operations = [
        migrations.RunPython(create_default_bill, reverse_code=noop_reverse),
        migrations.RemoveField(
            model_name="clientpayment",
            name="invoice",
        ),
        migrations.AddField(
            model_name="clientpayment",
            name="bill",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="billing.bill",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="PaymentInvoice",
        ),
    ]
