# Generated by Django 5.2.5 on 2025-09-17 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0009_delete_invoice_delete_invoiceitem_delete_quote_and_more"),
        (
            "transactions",
            "0007_remove_clientpayment_invoice_clientpayment_bill_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientpayment",
            name="bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="billing.bill",
            ),
        ),
    ]
