# Generated by Django 5.2.5 on 2025-09-11 12:44

import apps.core.models
import apps.crm.models.company
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wilayas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivitySector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nom du secteur d'activité"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Secteur d'activité",
                "verbose_name_plural": "Secteurs d'activité",
                "ordering": ["name"],
            },
            bases=(apps.core.models.CRUDUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CompanyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.FileField(
                        upload_to=apps.crm.models.company.company_document_upload_to,
                        verbose_name="File",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(apps.core.models.CRUDUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CompanyEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Primary"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CompanyPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phone", models.CharField(max_length=20, verbose_name="Phone")),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Primary"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "carte",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "hex_card",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("last_name", models.CharField(max_length=50, verbose_name="Nom")),
                ("first_name", models.CharField(max_length=50, verbose_name="Prénom")),
                (
                    "full_name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.text.Concat(
                            "first_name", models.Value(" "), "last_name"
                        ),
                        output_field=models.CharField(max_length=100),
                        verbose_name="Nom et prenom",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Poste"
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Service"
                    ),
                ),
                (
                    "civility",
                    models.CharField(
                        blank=True,
                        choices=[("MLL", "Mlle"), ("MME", "Mme"), ("MR", "Mr")],
                        default="MME",
                        max_length=3,
                        null=True,
                        verbose_name="Civilité",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contacts/photos",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Adresse"
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True,
                        default="Algérienne",
                        max_length=50,
                        null=True,
                        verbose_name="Nationalité",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Date de naissance",
                    ),
                ),
                (
                    "blood",
                    models.CharField(
                        choices=[
                            ("A-", "A-"),
                            ("A+", "A+"),
                            ("B-", "B-"),
                            ("B+", "B+"),
                            ("O-", "O-"),
                            ("O+", "O+"),
                            ("AB-", "AB-"),
                            ("AB+", "AB+"),
                        ],
                        max_length=3,
                        verbose_name="Groupe sanguin",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "dette",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "ordering": ("-created_at",),
            },
            bases=(apps.core.models.CRUDUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ContactEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Primary"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContactPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phone", models.CharField(max_length=20, verbose_name="Phone")),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Primary"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identifiant unique pour l'entreprise.",
                        max_length=100,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "business_owner",
                    models.CharField(
                        blank=True,
                        help_text="Nom de la personne responsable de l'entreprise.",
                        max_length=100,
                        null=True,
                        verbose_name="propriétaire d'entreprise",
                    ),
                ),
                (
                    "employees_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre d'employés"
                    ),
                ),
                (
                    "annual_tax",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Tax de formation annuel éstimé pour l'entreprise.",
                        max_digits=15,
                        null=True,
                        verbose_name="Tax de formation",
                    ),
                ),
                (
                    "annual_goal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Objectif commercial annuel de l'entreprise.",
                        max_digits=15,
                        null=True,
                        verbose_name="Objectif Annuel",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Website"),
                ),
                ("facebook", models.URLField(blank=True, null=True)),
                ("twitter", models.URLField(blank=True, null=True)),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("instagram", models.URLField(blank=True, null=True)),
                ("youtube", models.URLField(blank=True, null=True)),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Address"
                    ),
                ),
                (
                    "capital",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "nif",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="NIF"
                    ),
                ),
                (
                    "nrc",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="NRC"
                    ),
                ),
                (
                    "nart",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="NART"
                    ),
                ),
                (
                    "nis",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="NIS"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "activity_sectors",
                    models.ManyToManyField(
                        blank=True,
                        to="crm.activitysector",
                        verbose_name="Sécteur d'activité",
                    ),
                ),
                (
                    "commune",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="companies",
                        to="wilayas.commune",
                        verbose_name="Commune",
                    ),
                ),
            ],
            options={
                "verbose_name": "Société",
                "verbose_name_plural": "Sociétés",
                "ordering": ["-created_at"],
            },
            bases=(apps.core.models.CRUDUrlMixin, models.Model),
        ),
    ]
