# Generated by Django 5.2.5 on 2025-09-11 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("crm", "0001_initial"),
        ("tags", "0001_initial"),
        ("wilayas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_companies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="potentiel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="companies",
                to="core.potential",
                verbose_name="Potentiel",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags associés à l'entreprise.",
                related_name="companies",
                to="tags.tags",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="wilaya",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="companies",
                to="wilayas.wilaya",
                verbose_name="Wilaya",
            ),
        ),
        migrations.AddField(
            model_name="companydocument",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="crm.company",
            ),
        ),
        migrations.AddField(
            model_name="companyemail",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to="crm.company",
            ),
        ),
        migrations.AddField(
            model_name="companyphone",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phones",
                to="crm.company",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contacts",
                to="crm.company",
                verbose_name="Entreprise",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="source",
            field=models.ManyToManyField(
                blank=True,
                related_name="contacts_sources",
                to="core.leadsource",
                verbose_name="Source de contact",
            ),
        ),
        migrations.AddField(
            model_name="contactemail",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to="crm.contact",
            ),
        ),
        migrations.AddField(
            model_name="contactphone",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phones",
                to="crm.contact",
            ),
        ),
    ]
